# Generated by Django 3.0.7 on 2020-07-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle1', models.CharField(blank=True, max_length=255)),
                ('body1', models.TextField(blank=True)),
                ('subtitle2', models.CharField(blank=True, max_length=255)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('subtitle3', models.CharField(blank=True, max_length=255)),
                ('body2', models.TextField(blank=True)),
                ('subtitle4', models.CharField(blank=True, max_length=255)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image14', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image15', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image16', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('subtitle5', models.CharField(blank=True, max_length=255)),
                ('body3', models.TextField(blank=True)),
                ('subtitle6', models.CharField(blank=True, max_length=255)),
                ('image17', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('subtitle7', models.CharField(blank=True, max_length=255)),
                ('body4', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='posts', to='blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
