# Generated by Django 3.0.7 on 2020-07-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image18',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image19',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image20',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image21',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image22',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
