# Generated by Django 3.0.7 on 2020-07-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body11',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body12',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body13',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body14',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body15',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body16',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body17',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image23',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image24',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image25',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image26',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image27',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image28',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image29',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image30',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image31',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
