# Generated by Django 3.0.7 on 2020-07-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200706_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle8',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
