# Generated by Django 3.0.7 on 2020-10-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_subtitle8'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
