# Generated by Django 3.0.7 on 2020-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='frontimage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
